apiVersion: v1
kind: Service
metadata:
  name: frontend-kiosk-load-balancer-beta-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "k8s-beta-frontend-kiosk"
    service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "true"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    # kubernetes-beta-kiosk DO Certificate
    # *.kiosk.beta.mysimplaq.com
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "f6963db1-3946-441c-8abe-85bc33ef5874"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: frontend-kiosk-beta
    environment: beta
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80